conky.config = {
    own_window = true,
    own_window_type = 'normal',

    use_xft = true,
    override_utf8_locale = true,

    font = 'DejaVu Sans:size=20',

    alignment = 'top_left',
    gap_x = 100,
    gap_y = 100,

    minimum_width = 500,

    draw_shades = false,
    draw_outline = false,
    draw_borders = false,

    default_color = '#ffffff',
};

conky.text = [[
SUN: ☀
CLOUD: ☁
RAIN: ☂
STORM: ⚡
SNOW: ❄
FOG: ≋
]];
