conky.config = {
    alignment = 'top_left',

    background = false,
    border_width = 0,

    double_buffer = true,

    draw_borders = false,
    draw_graph_borders = false,
    draw_outline = false,
    draw_shades = false,

    use_xft = true,
    xftalpha = 1.0,
    override_utf8_locale = true,

    font = 'JetBrains Mono Nerd Font:size=14',

    gap_x = -5000,
    gap_y = -5000,

    own_window = true,
    own_window_class = 'StellarQuote',
    own_window_type = 'desktop',

    own_window_transparent = true,
    own_window_argb_visual = true,
    own_window_argb_value = 0,

    own_window_hints = 'undecorated,below,sticky,skip_taskbar,skip_pager',

    update_interval = 60,

    minimum_width = 0,
    minimum_height = 0,

    use_spacer = 'none',
};

conky.text = [[
${alignc}${color #d8d8d8}The secret of getting ahead
${alignc}is getting started.
${voffset 1}
${alignc}${color #a8a8a8}— Mark Twain
]]


