conky.config = {
    alignment = 'top_left',

    background = false,
    border_width = 0,

    double_buffer = true,

    draw_borders = false,
    draw_graph_borders = false,
    draw_outline = false,
    draw_shades = false,

    use_xft = true,
    xftalpha = 1.0,
    override_utf8_locale = true,

    font = 'JetBrains Mono Nerd Font:size=10',

    gap_x = -5000,
    gap_y = -5000,

    own_window = true,
    own_window_class = 'StellarLeft',
    own_window_type = 'desktop',

    own_window_transparent = true,
    own_window_argb_visual = true,
    own_window_argb_value = 0,

    own_window_hints = 'undecorated,below,sticky,skip_taskbar,skip_pager',

    update_interval = 1,

    minimum_width = 0,
    minimum_height = 0,

    use_spacer = 'none',
};

conky.text = [[
${color #e6a65d}| CPU:       ${color #e5e5e5}${cpu}%
${voffset 0.5}
${color #82b8d9}| RAM:       ${color #e5e5e5}${memperc}%
${voffset 0.5}
${color #72c4b0}| NET ↓:     ${color #e5e5e5}${downspeed wlo1}/s
${voffset 0.5}
${color #d987a8}| NET ↑:     ${color #e5e5e5}${upspeed wlo1}/s
${voffset 0.5}
${color #d6b36a}| SSD:       ${color #e5e5e5}${fs_used /} / ${fs_size /}
${voffset 0.5}
${color #b89bd4}| HDD:       ${color #e5e5e5}${fs_used /home/abby/LinuxData} / ${fs_size /home/abby/LinuxData}
${voffset 0.5}
${color #d98b72}| Distro:    ${color #e5e5e5}Linux Mint 22.3
${voffset 0.5}
${color #8fa9e0}| Desktop:   ${color #e5e5e5}Cinnamon 6.6.9
${voffset 0.5}
${color #c58b72}| WM:        ${color #e5e5e5}Muffin
]]
